targets:
    $default:
        builders:
            graphql_codegen:
                options:
                    clients:
                        - graphql
                        - graphql_flutter
                    addTypenameExcludedPaths:
                        - subscription
                    scalars:
                        ColorCode:
                            type: Color
                            fromJsonFunctionName: jsonToColor
                            toJsonFunctionName: colorToJson
                            import: package:bofe/graphql/scalars.dart
                        JSONObject:
                            type: Map<String, dynamic>
                        DateTime:
                            type: DateTime
                        NaiveDate:
                            type: DateTime
                            toJsonFunctionName: dateToJson
                            import: package:bofe/graphql/scalars.dart
                        Duration:
                            type: Duration
                            fromJsonFunctionName: jsonToDuration
                            import: package:bofe/graphql/scalars.dart
                        Upload:
                            type: MultipartFile
                            import: package:http/http.dart
                        Url:
                            type: Uri
                            fromJsonFunctionName: jsonToUri
                            import: package:bofe/graphql/scalars.dart
                        UUID:
                            type: String
